services:
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    volumes:
      - static_volume:/app/dist
 
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - web
    volumes:
      - static_volume:/app/dist

volumes:
  static_volume:
